name := "BitcoinTwitter"
version := "1.0"
scalaVersion := "2.11.12"
libraryDependencies += "com.google.api-client" % "google-api-client" % "1.20.0"
libraryDependencies += "com.google.oauth-client" % "google-oauth-client" % "1.23.0"
libraryDependencies += "com.google.oauth-client" % "google-oauth-client-java6" % "1.23.0"
libraryDependencies += "com.google.oauth-client" % "google-oauth-client-jetty" % "1.23.0"
libraryDependencies += "com.google.apis" % "google-api-services-youtube" % "v3-rev182-1.22.0"
//libraryDependencies += "org.apache.kafka" %% "kafka" % "0.8.2.1"
libraryDependencies += "org.apache.kafka" %% "kafka" % "0.10.2.1"
libraryDependencies += "com.typesafe" % "config" % "1.3.2"
libraryDependencies += "org.apache.zookeeper" % "zookeeper" % "3.4.11"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-stream-core" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-gdax" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-bitstamp" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-poloniex" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-coinmate" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-okcoin" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-bitfinex" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-gemini" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-binance" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-poloniex2" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-bitflyer" % "4.3.1"
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-wex" % "4.3.1"
libraryDependencies += "org.java-websocket" % "Java-WebSocket" % "1.3.8"
////twitter apis
libraryDependencies += "org.twitter4j" % "twitter4j-core" % "4.0.6"
libraryDependencies += "org.twitter4j" % "twitter4j-stream" % "4.0.6"
libraryDependencies +="edu.stanford.nlp" % "stanford-corenlp" % "3.6.0"
//libraryDependencies +="org.apache.spark" %% "spark-core" % "1.6.2"
libraryDependencies +="org.apache.spark" %% "spark-core" % "2.1.0"
//libraryDependencies +="org.apache.spark" %% "spark-streaming" % "1.6.2"
libraryDependencies +="org.apache.spark" %% "spark-streaming" % "2.1.0"
//libraryDependencies += "org.apache.spark" %% "spark-streaming-kafka" % "1.6.2"
libraryDependencies += "org.apache.spark" %% "spark-streaming-kafka-0-10" % "2.1.0"
libraryDependencies += "com.google.code.gson" % "gson" % "2.6.2"
//override 2.9.7 jackson dependencies
dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-core" % "2.8.7"
dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-databind" % "2.8.7"
dependencyOverrides += "com.fasterxml.jackson.module" % "jackson-module-scala_2.11" % "2.8.7"
val workaround = {
  sys.props += "packaging.type" -> "jar"
  ()
}